<h1><?php echo $this->identity()->getUsername(); ?></h1>
<ul id="userSettingsTabs">
    <?php
    $pages = array(
        $this->translate('games'),
        $this->translate('feeds'),
        $this->translate('details'),
        $this->translate('socials'),
        $this->translate('following'),
    );
    foreach($pages as $page):
        ?>
        <li<?php echo ($page == $this->activePage) ? ' class="active"' : ''; ?>><a href="<?php echo $this->url('user/' . $page); ?>" title="<?php echo ucfirst($page); ?>"><?php echo ucfirst($page); ?></a></li>
    <?php endforeach; ?>
</ul>