<?php
if(isset($form)):
	echo '<h2>' . $this->translate('Edit Account') . '</h2>';
$form -> prepare();
$form -> setAttributes(array('id'=> 'updateForm', 'name' => 'updateForm'));
$form -> setAttribute('action', 'accounts');
?>
<?php 
	echo $this->form()->openTag($form);

 #echo $this->formElementErrors($form->get('identity')) 
	$fieldSet = $form->get('user');

	echo $this->formHidden($form->get('security')); 
	echo $this->formHidden($fieldSet->get('id')); ?>

	<div class="element">
		<?php 
		 	echo $this->formElementErrors($fieldSet->get('username'),array('class'=>'formError')) ;
			echo $this->formLabel($fieldSet->get('username'));
			echo $this->formInput($fieldSet->get('username'));
		?>
	</div>
	
	<div class="element">
		<?php 
		 	echo $this->formElementErrors($fieldSet->get('password'),array('class'=>'formError')) ;
			echo $this->formLabel($fieldSet->get('password'));
			echo $this->formInput($fieldSet->get('password'));
		?>
	</div>
	
	<div class="element">
		<?php 
		 	echo $this->formElementErrors($fieldSet->get('email'),array('class'=>'formError')) ;
			echo $this->formLabel($fieldSet->get('email'));
			echo $this->formInput($fieldSet->get('email'));
		?>
	</div>


<div class="element">
	<?php echo $this -> formSubmit($form -> get('submit')->setValue($this -> translate('Update'))); ?>
</div>

<?php 
echo $this->form()->closeTag();
endif;
?>