<div id="main">
	<div id="controls">
		<ul class="tab-list">
			<li class="tableList tab-active"><?php echo $this -> translate("Account List"); ?></li>
			<li class="addForm"><?php echo $this -> translate("Add Account"); ?></li>
		</ul>
	</div>	
	<div id="tableList" class="tab">
		<table>
			<caption><?php echo $this -> translate("Account List"); ?></caption>
			<thead>
				<tr>
					<?php 
						$headerParams = array($this->translate('username') => 'username',
											$this->translate('password') => 'password',
											$this->translate('email') => 'email');
											
						foreach($headerParams as $header => $sortName):
							$isActiveSort = false;
							$sortType = 'asc';
							if(isset($sort) && ($sort == $header || $sort == $sortName)){
								$isActiveSort = true;
								if($type == 'asc') $sortType = 'desc';
							}
					?>
					<th<?php echo $isActiveSort ? ' class="sortActive"' : ''; ?>>
						<a href="<?php echo $this->url('admin_main/accounts',array('action' => 'list','sort' => $sortName, 'type' => $sortType),null,true); ?>"><?php echo mb_convert_case($header, MB_CASE_TITLE, "UTF-8"); ?></a>
					</th>
					
					<?php endforeach; ?>
					<th><?php echo $this -> translate("Edit"); ?></th>
					<th><?php echo $this -> translate("Delete"); ?></th>		
				</tr>	
			</thead>
			<tbody>
				<?php 
				if($paginator->getTotalItemCount() > 0){
					echo '<tbody>';
					foreach($paginator as $entity): ?>	
					<tr class="dataItem accounts" id="data-<?php echo $entity->getId(); ?>">
						<td class="username"><?php echo$this->escapeHtml($entity->getUsername()); ?></td>
						<td class="password">**************</td>
						<td class="email"><?php echo is_null($entity->getEmail()) ? ' - ' : $this->escapeHtml($entity->getEmail()); ?></td>
						<td class="edit"><img src="<?php echo $this->basePath() . '/images/edit-icon.png';?>" /></td>
						<td class="delete"><img src="<?php echo $this->basePath() . '/images/delete-icon.png';?>" /></td>
					</tr>
					<?php 
					endforeach; 
					echo '</tbody></table>';
				}else{ ?>
					</table>
					<div class="notFound"><?php echo $this -> translate("There are no accounts available."); ?></div>
				<?php } ?>
		</table>
		<?php echo $this->paginationControl($paginator,
		                                    'Sliding',
		                                    array('partial/paginator.phtml','Account'), array('route' => 'admin_main/accounts')); ?>	
	</div>
	<div id="addForm" class="tab inactive">
		<h1><?php echo $this -> translate("Add A New Account"); ?></h1>
		<div id="actions">
			<?php
			$form -> prepare();
			$form -> setAttribute('action', $this->url('admin_main/accounts'));
			?>
			<?php 
				echo $this->form()->openTag($form);
			
				$fieldSet = $form->get('user');
			
				echo $this->formHidden($form->get('security')); 
				echo $this->formHidden($fieldSet->get('id')); ?>
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('username'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('username'));
					echo $this->formInput($fieldSet->get('username'));
				?>
			</div>
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('password'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('password'));
					echo $this->formInput($fieldSet->get('password'));
				?>
			</div>
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('email'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('email'));
					echo $this->formInput($fieldSet->get('email'));
				?>
			</div>
			
			
			<div class="element">
				<?php echo $this -> formSubmit($form -> get('submit')->setValue($this -> translate('Add'))); ?>
			</div>
			
			<?php echo $this->form()->closeTag()
			?>
		</div>  		
	</div>
</div> 