<?php
if(isset($form)):
	echo '<h2>' . $this->translate('Edit Content Info') . '</h2>';
		$form -> prepare();
		$form -> setAttribute('action', 'general');
		$form -> setAttributes(array('id'=> 'updateForm', 'name' => 'updateForm'));

?>
<?php
	echo $this -> form() -> openTag($form);

	$fieldSet = $form -> get('general');

	echo $this -> formHidden($form -> get('security'));
	echo $this -> formHidden($fieldSet -> get('id'));
?>

<div class="element">
	<?php
	echo $this -> formElementErrors($fieldSet -> get('content'), array('class' => 'formError'));
	echo $this -> formLabel($fieldSet -> get('content'));
	echo $this -> FormTextarea($fieldSet -> get('content'));
	?>
</div>

<div class="element">
	<?php
	echo $this -> formElementErrors($fieldSet -> get('contentEn'), array('class' => 'formError'));
	echo $this -> formLabel($fieldSet -> get('contentEn'));
	echo $this -> FormTextarea($fieldSet -> get('contentEn'));
	?>
</div>

<div class="element">
	<?php echo $this -> formSubmit($form -> get('submit') -> setValue($this -> translate('Update'))); ?>
</div>

<?php 
echo $this->form()->closeTag();
endif;
?>