<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Account\Module'                       => __DIR__ . '/Module.php',
  'Account\Controller\AccountController' => __DIR__ . '/src/Account/Controller/AccountController.php',
  'Account\Entity\Account'               => __DIR__ . '/src/Account/Entity/Account.php',
  'Account\Entity\AccountsSocials'       => __DIR__ . '/src/Account/Entity/AccountsSocials.php',
  'Account\Entity\Group'                 => __DIR__ . '/src/Account/Entity/Group.php',
  'Account\Form\LoginFieldset'           => __DIR__ . '/src/Account/Form/LoginFieldset.php',
  'Account\Form\LoginForm'               => __DIR__ . '/src/Account/Form/LoginForm.php',
  'Account\Form\RegisterFieldset'        => __DIR__ . '/src/Account/Form/RegisterFieldset.php',
  'Account\Form\RegisterForm'            => __DIR__ . '/src/Account/Form/RegisterForm.php',
  'Account\Model\AuthStorage'            => __DIR__ . '/src/Account/Model/AuthStorage.php',
  'Account\Plugin\ActiveAccount'         => __DIR__ . '/src/Account/Plugin/ActiveAccount.php',
  'Account\Repository\AccountRepository' => __DIR__ . '/src/Account/Repository/AccountRepository.php',
  'Account\Service\Account'              => __DIR__ . '/src/Account/Service/Account.php',
  'Account\View\Helper\User'             => __DIR__ . '/src/Account/View/Helper/User.php',
);
