<div id="main">
	<div id="controls">
		<ul class="tab-list">
			<li class="tableList tab-active"><?php echo $this -> translate("Film List"); ?></li>
			<li class="addForm"><?php echo $this -> translate("Add Film"); ?></li>
		</ul>
	</div>
	<div id="tableList" class="tab">
		<table>
			<caption><?php echo $this -> translate("Film List"); ?></caption>
			<thead>
				<tr>
					<?php 
						$headerParams = array(
											$this->translate('name') => 'name',
											$this->translate('translated name') => 'nameEn',
											$this->translate('description') => 'description',
											$this->translate('translated description') => 'descriptionEn',
											$this->translate('video') => 'video',
											$this->translate('categories') => 'categories',
											$this->translate('date') => 'postTime',
											$this->translate('snapshot') => 'snapshot',
											$this->translate('show in slide') => 'inSlide',
											);
											
						foreach($headerParams as $header => $sortName):
							$isActiveSort = false;
							$sortType = 'asc';
							if(isset($sort) && ($sort == $header || $sort == $sortName)){
								$isActiveSort = true;
								if($type == 'asc') $sortType = 'desc';
							}
					?>
					<th<?php echo $isActiveSort ? ' class="sortActive"' : ''; ?>>
						<a href="<?php echo $this->url('admin_main/films',array('action' => 'list','sort' => $sortName, 'type' => $sortType),null,true); ?>"><?php echo mb_convert_case($header, MB_CASE_TITLE, "UTF-8"); ?></a>
					</th>
					
					<?php endforeach; ?>
					<th><?php echo $this -> translate("Edit"); ?></th>
					<th><?php echo $this -> translate("Delete"); ?></th>		
				</tr>	
			</thead>
				<?php 
				if($paginator->getTotalItemCount() > 0){
					echo '<tbody>';
					foreach($paginator as $entity): ?>				
					<tr class="dataItem films" id="data-<?php echo $entity->getId(); ?>">
						<td class="name"><?php echo $this->escapeHtml($entity->getName()); ?></td>
						<td class="nameEn"><?php echo $this->escapeHtml($entity->getNameEn()); ?></td>
						<td class="description"><?php echo $this->escapeHtml($entity->getDescription()); ?></td>
						<td class="descriptionEn"><?php echo $this->escapeHtml($entity->getDescriptionEn()); ?></td>
						<td class="video"><a href="<?php echo $entity->getVideo(); ?>" target="_blank">Click Here</a></td>
						<td class="categories"><?php echo implode(', <br/>',$entity->getCategoriesNames()); ?></td>
						<td class="postTime"><?php echo $entity->getPostTime(); ?></td>
						<td class="snapshot"><?php $snap = $entity->getSnapshot(); if(!empty($snap) && !is_null($snap)) : ?><img src="<?php echo $this->basePath() . '/videos/' . $entity->getSnapshot();  ?>" /><?php endif; ?></td>
						<td class="snapshot"><input type="checkbox" disabled="disabled" <?php echo ($entity->getInSlide() == 1) ? ' checked="checked"' : ''; ?> /></td>
						<td class="edit"><img src="<?php echo $this->basePath() . '/images/edit-icon.png';?>" /></td>
						<td class="delete"><img src="<?php echo $this->basePath() . '/images/delete-icon.png';?>" /></td>
					</tr>
					<?php 
					endforeach; 
					echo '</tbody></table>';
				}else{ ?>
					</table>
					<div class="notFound"><?php echo $this -> translate("There are no sponsors available."); ?></div>
				<?php } ?>
		<?php echo $this->paginationControl($paginator,
		                                    'Sliding',
		                                    array('partial/paginator.phtml','Category'), array('route' => 'admin_main/categories')); ?>	
	</div> 
	<div id="addForm" class="tab inactive">
		<h1><?php echo $this -> translate("Add A New Film"); ?></h1>
			<div id="actions">
				<?php
				$form -> prepare();
				$form -> setAttribute('action', $this->url('admin_main/films'));
				?>
				<?php 
					echo $this->form()->openTag($form);
				
					$fieldSet = $form->get('film');
				
					echo $this->formHidden($form->get('security')); 
					echo $this->formHidden($fieldSet->get('id')); ?>
				
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('name'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('name'));
						echo $this->formInput($fieldSet->get('name'));
					?>
				</div>	
		
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('nameEn'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('nameEn'));
						echo $this->formInput($fieldSet->get('nameEn'));
					?>
				</div>	
				
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('description'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('description'));
						echo $this->formInput($fieldSet->get('description'));
					?>
				</div>	
				
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('descriptionEn'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('descriptionEn'));
						echo $this->formInput($fieldSet->get('descriptionEn'));
					?>
				</div>					
		
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('postTime'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('postTime'));
						echo $this->formInput($fieldSet->get('postTime'));
					?>
					<div gldp-el="mydate"
				         style="width:400px; height:300px; position:absolute; display:none;">
				    </div>			
				</div>
		
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('categories'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('categories'));
						echo $this->formSelect($fieldSet->get('categories'));
					?>
				</div>	
		
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('video'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('video'));
						echo $this->formInput($fieldSet->get('video'));
					?>
				</div>	
				
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('snapshot'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('snapshot'));
						echo $this->formFile($fieldSet->get('snapshot'));
					?>
				</div>
				
				<div class="element">
					<?php 
					 	echo $this->formElementErrors($fieldSet->get('inSlide'),array('class'=>'formError')) ;
						echo $this->formLabel($fieldSet->get('inSlide'));
						echo $this->formCheckbox($fieldSet->get('inSlide'));
					?>
				</div>				
				
				<div class="element">
					<?php echo $this -> formSubmit($form -> get('submit')->setValue($this -> translate('Add'))); ?>
				</div>
				
				<?php echo $this->form()->closeTag()
				?>
			</div>    			
		</div>	
</div>
