<div id="main">
	<div id="controls">
		<ul class="tab-list">
			<li class="tableList tab-active"><?php echo $this -> translate("Member List"); ?></li>
			<li class="addForm"><?php echo $this -> translate("Add Member"); ?></li>
		</ul>
	</div>	
	<div id="tableList" class="tab">
		<table>
			<caption><?php echo $this -> translate("Member List"); ?></caption>
			<thead>
				<tr>
					<?php 
						$headerParams = array(
											$this->translate('name') => 'name',
											$this->translate('position') => 'position',
											$this->translate('translated position') => 'positionEn',
											$this->translate('avatar') => 'avatar',
											$this->translate('email') => 'email'
											);
											
						foreach($headerParams as $header => $sortName):
							$isActiveSort = false;
							$sortType = 'asc';
							if(isset($sort) && ($sort == $header || $sort == $sortName)){
								$isActiveSort = true;
								if($type == 'asc') $sortType = 'desc';
							}
					?>
					<th<?php echo $isActiveSort ? ' class="sortActive"' : ''; ?>>
						<a href="<?php echo $this->url('admin_main/team',array('action' => 'list','sort' => $sortName, 'type' => $sortType),null,true); ?>"><?php echo mb_convert_case($header, MB_CASE_TITLE, "UTF-8"); ?></a>
					</th>
					
					<?php endforeach; ?>
					<th><?php echo $this -> translate("Edit"); ?></th>
					<th><?php echo $this -> translate("Delete"); ?></th>		
				</tr>	
			</thead>
				<?php 
				if($paginator->getTotalItemCount() > 0){
					echo '<tbody>';
					foreach($paginator as $entity): ?>				
					<tr class="dataItem team" id="data-<?php echo $entity->getId(); ?>">
						<td class="name"><?php echo $this->escapeHtml($entity->getName()); ?></td>
						<td class="position"><?php echo $this->escapeHtml($entity->getPosition()); ?></td>
						<td class="positionEn"><?php echo $this->escapeHtml($entity->getPositionEn()); ?></td>
						<td class="avatar"><img src="<?php echo $this->basePath() . '/images/users/' . $entity->getAvatar(); ?>" /></td>
						<td class="email"><?php echo $this->escapeHtml($entity->getEmail()); ?></td>
						<td class="edit"><img src="<?php echo $this->basePath() . '/images/edit-icon.png';?>" /></td>
						<td class="delete"><img src="<?php echo $this->basePath() . '/images/delete-icon.png';?>" /></td>
					</tr>
					<?php 
					endforeach; 
					echo '</tbody></table>';
				}else{ ?>
					</table>
					<div class="notFound"><?php echo $this -> translate("There are no members available."); ?></div>
				<?php } ?>
		<?php echo $this->paginationControl($paginator,
		                                    'Sliding',
		                                    array('partial/paginator.phtml','Category'), array('route' => 'admin_main/categories')); ?>	
	</div>
	<div id="addForm" class="tab inactive">
		<h1><?php echo $this -> translate("Add A New Team Member"); ?></h1>
		<div id="actions">
			<?php
			$form -> prepare();
			$form -> setAttribute('action', $this->url('admin_main/team'));
			?>
			<?php 
				echo $this->form()->openTag($form);
			
				$fieldSet = $form->get('member');
			
				echo $this->formHidden($form->get('security')); 
				echo $this->formHidden($fieldSet->get('id')); ?>
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('name'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('name'));
					echo $this->formInput($fieldSet->get('name'));
				?>
			</div>
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('position'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('position'));
					echo $this->formInput($fieldSet->get('position'));
				?>
			</div>
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('positionEn'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('positionEn'));
					echo $this->formInput($fieldSet->get('positionEn'));
				?>
			</div>		
	
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('avatar'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('avatar'));
					echo $this->formFile($fieldSet->get('avatar'));
				?>
			</div>	
			
			<div class="element">
				<?php 
				 	echo $this->formElementErrors($fieldSet->get('email'),array('class'=>'formError')) ;
					echo $this->formLabel($fieldSet->get('email'));
					echo $this->formInput($fieldSet->get('email'));
				?>
			</div>			
			
			<div class="element">
				<?php echo $this -> formSubmit($form -> get('submit')->setValue($this -> translate('Add'))); ?>
			</div>
			
			<?php echo $this->form()->closeTag()
			?>
		</div>   		
	</div>
</div> 