<?php
echo '<h2 class="newPost">' . $this->translate('Post A New Feed') . '</h2>';
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url('feed/new'),
    'id' => 'feedForm'));
echo $this->form()->openTag($form);
$fieldSet = $form->get('feed');

echo $this->formHidden($form->get('security'));
?>

    <div class="element">
        <p class="formNote"><?php echo $this->translate('If you leave this blank the title from the youtube video will be used.'); ?></p>
        <?php
        echo $this->formElementErrors($fieldSet->get('title'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('title'));
        echo $this->formInput($fieldSet->get('title'));
        ?>
        <p>Remaining characters: <span class="remainingChars">50</span>/50</p>
    </div>

    <div class="element">
        <p class="formNote"><?php echo $this->translate('If you leave it blank the description from the youtube video will be used.'); ?></p>
        <?php
        echo $this->formElementErrors($fieldSet->get('description'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('description'));
        echo $this->formTextarea($fieldSet->get('description'));
        ?>
        <p>Remaining characters: <span class="remainingChars">200</span>/200</p>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('video'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('video'));
        echo $this->formInput($fieldSet->get('video'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('game'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('game'));
        echo $this->formSelect($fieldSet->get('game'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('category'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('category'));
        echo $this->formSelect($fieldSet->get('category'));
        ?>
    </div>

    <div class="element">
        <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Submit'))); ?>
    </div>

<?php
echo $this->form()->closeTag();
?>