<?php
echo '<h2>' . $this->translate('Post A New Feed') . '</h2>';
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url('feed/new'),
    'id' => 'feedForm'));
echo $this->form()->openTag($form);
$fieldSet = $form->get('feed');

echo $this->formHidden($form->get('security'));
?>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('title'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('title'));
        echo $this->formInput($fieldSet->get('title'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('video'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('video'));
        echo $this->formInput($fieldSet->get('video'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('game'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('game'));
        echo $this->formSelect($fieldSet->get('game'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldSet->get('category'), array('class' => 'formError'));
        echo $this->formLabel($fieldSet->get('category'));
        echo $this->formSelect($fieldSet->get('category'));
        ?>
    </div>

    <div class="element">
        <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Submit'))); ?>
    </div>

<?php
echo $this->form()->closeTag();
?>