<?php echo $this->doctype(); ?>

<?php
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>		
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Absurd'); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                      #  ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/glDatePicker.default.css')
                        #->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/lib.js')
                                      ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))		
									  ->prependFile($this->basePath() . '/js/jquery-1.9.0.js'); ?>
      	<script>
			var baseUrl = '<?php echo $this->basePath(); ?>';
		</script>		
    </head>
    <body class="mainPage<?php echo (isset($child->bodyClass)) ? ' ' . $child->bodyClass : '';?>">
		<noscript>
			<div id="nojs">
				<?php echo $this->translate("Please enable javascript for the site to work properly.");?>
			</div>
		</noscript>    	
        <header>
        	<nav>
        		<ul>
        			<li><a href="<?php echo $this->url('home'); ?>"><?php echo mb_strtoupper($this->translate('home'),'UTF-8'); ?></a></li>
        			<li><a href="<?php echo $this->url('portfolio'); ?>"><?php echo mb_strtoupper($this->translate('portfolio'),'UTF-8'); ?></a></li>
        			<li id="logo"><a href="<?php echo $this->url('home'); ?>"></a></li>
        			<li id="languageChange">
        				<a href="<?php echo $this->url('language',array('lang' => 'en')); ?>"><img src="<?php echo $this->basePath() . '/images/english-icon.png' ;?>" /></a>
        				<a href="<?php echo $this->url('language',array('lang' => 'no')); ?>"><img src="<?php echo $this->basePath() . '/images/norway-icon.png' ;?>" /></a>
        				
        			</li>
        			<li><a href="<?php echo $this->url('team'); ?>"><?php echo mb_strtoupper($this->translate('team'),'UTF-8'); ?></a></li>
        			<li><a href="#contact"><?php echo mb_strtoupper($this->translate('contact'),'UTF-8'); ?></a></li>
        		</ul>
        	</nav>
        	<div id="slider">
        			<?php 
						$firstFilm = $child->slideFilms[0];
						if(!empty($firstFilm)){
			 			$snap = $firstFilm->getSnapshot(); 
        			
        			?>
        		<div id="displayedSlide" class="slide-<?php echo $firstFilm->getVideoId(); ?>">
						<img src="<?php echo $this->basePath() . '/images/slider-play-icon.png'; ?>" class="slidePlay hoverable" />
						<img src="<?php echo (!empty($snap)) ? $this->basePath() . '/videos/' . $firstFilm->getSnapshot() : $firstFilm->getVimeoThumb('large'); ?>" class="snapshot" />
        		</div>
        		<div id="slideNavigation">
						<img src="<?php echo $this->basePath() . '/images/left-arrow.png'; ?>" id="leftSlideArrow" />
						<span class="filmDescription">
							<?php if($child->locale == 'en_US'){
								echo $this->escapeHtml($firstFilm->getDescriptionEn());
							}else{
								echo $this->escapeHtml($firstFilm->getDescription());
							} ?>
						</span>
						<img src="<?php echo $this->basePath() . '/images/right-arrow.png'; ?>" id="rightSlideArrow" />
        		</div>
				<div id="hiddenSlides">
					<?php 
						$slideList = $child->slideFilms;
						array_shift($slideList);
						foreach($slideList as $slide){
							$snap = $slide->getSnapshot(); 
					?>
						<div class="slide-<?php echo $slide->getVideoId(); ?>">
							<img src="<?php echo (!empty($snap)) ? $this->basePath() . '/videos/' . $slide->getSnapshot() : $slide->getVimeoThumb('large'); ?>" class="snapshot" />							
							<span class="filmDescription">
								<?php if($child->locale == 'en_US'){
									echo $this->escapeHtml($slide->getDescriptionEn());
								}else{
									echo $this->escapeHtml($slide->getDescription());
								} ?>
							</span>
						</div>
					<?php }
					?>
				</div>	
				<?php } ?>
        	</div>
        </header>      
        	<div id="content">
            	<?php echo $this->content; ?>
            </div>
        <footer>       	
        	<a name="contact"></a>
			<video autoplay="autoplay" loop="loop" muted="muted">
			  <source src="<?php echo $this->basePath() . '/videos/footer-video.mp4';?>" type="video/mp4">
			  <source src="<?php echo $this->basePath() . '/videos/footer-video.webm';?>" type="video/webm">
			Your browser does not support the video tag.
			</video>    
			<div id="contact">		
				<h1><?php echo $this->translate('Contact'); ?></h1>
				<span class="underline"></span>
				<ul class="info">
					<li>
						<h2><?php echo $this->translate('email:');?></h2>
						<a href="mailto:<?php echo $child->general['email'];?>"><?php echo $child->general['email'];?></a>
					</li>
					<li>
						<h2><?php echo $this->translate('phone:');?></h2>
						<?php echo $child->general['phone'];?>
					</li>					
				</ul>
				<ul class="social">
					<li>
						<a href="<?php echo $child->general['vimeo'];?>"><img src="<?php echo $this->basePath() . '/images/vimeo-icon.png';?>" target="_blank" /></a>
					</li>
					<li>
						<a href="<?php echo $child->general['youtube'];?>"><img src="<?php echo $this->basePath() . '/images/youtube-icon.png';?>" target="_blank" /></a>
					</li>					
					<li>
						<a href="<?php echo $child->general['twitter'];?>"><img src="<?php echo $this->basePath() . '/images/twitter-icon.png';?>" target="_blank" /></a>
					</li>
					<li>
						<a href="<?php echo $child->general['facebook'];?>"><img src="<?php echo $this->basePath() . '/images/facebook-icon.png';?>" target="_blank" /></a>
					</li>
				</ul>
			</div> 
        </footer>        
      <?php echo $this->inlineScript()->prependFile($this->basePath() . '/js/main-1.0.0.js', 'text/javascript'); ?>
        
    </body>
</html>
