<?php echo $this->doctype(); ?>

<?php
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>		
<html lang="en">
    <head>
        <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>          
        <?php echo $this->headTitle('Leetfeed'); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                      #  ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/glDatePicker.default.css')
                        #->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/lib.js')
                                      ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))		
									  ->prependFile($this->basePath() . '/js/jquery-1.9.0.js'); ?>
      	<script>
			var baseUrl = '<?php echo $this->basePath(); ?>';
		</script>
    </head>
    <body<?php echo (isset($child->bodyClass)) ? ' class="' . $child->bodyClass . '"' : '';?>>
		<noscript>
			<div id="nojs">
				<?php echo $this->translate("Please enable javascript for the site to work properly.");?>
			</div>
		</noscript>
        <?php
        $messages = $this->flashMessenger()->getMessages();
        if(!empty($messages)) :
            ?>
            <div id="flash">
                <ul class="flashMessages">
                    <?php foreach ($messages as $fMessage) : ?>
                        <li><?php echo $fMessage; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <header>
            <div id="topWrapper">
                <div id="logo">
                    <a href="<?php echo $this->url('home'); ?>" title="<?php echo $this->translate("Return to home"); ?>">Logo</a>
                </div>
                <?php if(!$this->identity()){ ?>
                    <div id="connect">
                        <a href="<?php echo $this->url('login'); ?>" title="<?php echo $this->translate('Login'); ?>"><?php echo $this->translate('Login'); ?></a>
                        <a href="<?php echo $this->url('register'); ?>" title="<?php echo $this->translate('Register'); ?>"><?php echo $this->translate('Register'); ?></a>
                    </div>
                <?php }else{ ?>
                    <nav>
                        <ul>
                            <li>
                                <a href="<?php echo $this->url('profile',array('user' => $user->getUsername())); ?>" title="<?php echo $this->translate("My Profile"); ?>">

                                    <?php echo ucfirst($user->getUsername()); ?>
                                </a>
                            </li>
                            <li><a href="<?php echo $this->url('games'); ?>" title="<?php echo $this->translate("Games List"); ?>"><?php echo $this->translate('Games'); ?></a></li>
                            <li><a href="<?php echo $this->url('user/games'); ?>" title="<?php echo $this->translate('Settings'); ?>"><img src="<?php echo $this->basePath() . '/images/settings-icon.png';  ?>" alt="settings" class="hoverable" /></a></li>
                            <li><a href="<?php echo $this->url('logout'); ?>" title="<?php echo $this->translate('Logout'); ?>"><img src="<?php echo $this->basePath() . '/images/logout-icon.png';  ?>" alt="logout" class="hoverable" /></a></li>
                        </ul>
                    </nav>
                <?php } ?>
            </div>
        </header>
        <div id="content">
            <?php echo $this->content; ?>
        </div>
        <footer>
        </footer>        
      <?php echo $this->inlineScript()->prependFile($this->basePath() . '/js/main-1.0.0.js', 'text/javascript'); ?>
        
    </body>
</html>
