<?php
if(isset($form)):
	echo '<h2>' . $this->translate('Edit Category') . '</h2>';
$form -> prepare();
$form -> setAttributes(array('id'=> 'updateForm', 'name' => 'updateForm'));
$form -> setAttribute('action', 'categories');
?>
<?php 
	echo $this->form()->openTag($form);

 #echo $this->formElementErrors($form->get('identity')) 
	$fieldSet = $form->get('category');

	echo $this->formHidden($form->get('security')); 
	echo $this->formHidden($fieldSet->get('id')); ?>

	<div class="element">
		<?php 
		 	echo $this->formElementErrors($fieldSet->get('name'),array('class'=>'formError')) ;
			echo $this->formLabel($fieldSet->get('name'));
			echo $this->formInput($fieldSet->get('name'));
		?>
	</div>
	
	<div class="element">
		<?php 
		 	echo $this->formElementErrors($fieldSet->get('nameEn'),array('class'=>'formError')) ;
			echo $this->formLabel($fieldSet->get('nameEn'));
			echo $this->formInput($fieldSet->get('nameEn'));
		?>
	</div>

	<div class="element">
		<?php 
		 	echo $this->formElementErrors($fieldSet->get('position'),array('class'=>'formError')) ;
			echo $this->formLabel($fieldSet->get('position'));
			echo $this->formInput($fieldSet->get('position'));
		?>
	</div>

<div class="element">
	<?php echo $this -> formSubmit($form -> get('submit')->setValue($this -> translate('Update'))); ?>
</div>

<?php 
echo $this->form()->closeTag();
endif;
?>