<?php
/**
 * @var $user \Account\Entity\Account
 */
$user = $this->user();
$gameName = $game->getName();
$urlName = $game->getUrlName();
?>
<aside>
    <a href="<?php echo $this->url('game/profile', array('name' => $urlName)); ?>"
       title="<?php echo $this->translate(sprintf("Visit %s's profile.", $gameName)); ?>"
       id="activeGame-<?php echo $game->getId(); ?>">
        <img id="gameFeedLogo" src="<?php echo $this->basePath() . '/images/' . $game->getAvatar(); ?>-feeds.jpg"/>
    </a>
    <ul id="gameCategories">
        <?php
        $categories = array($this->translate("feeds") => $this->translate("Generated Feeds From Youtube"),
            $this->translate("favorites") => $this->translate("Feeds you marked as favorite from") . " {$gameName}",
            $this->translate("leet") => $this->translate("Feeds you marked as Leet from") . " {$gameName}",
            $this->translate("history") => $this->translate("Feeds you watched from") . " {$gameName}");
        foreach ($categories as $categoryName => $categoryTitle):
            ?>
            <li<?php echo ($categoryName == $category) ? ' class="active"' : ''; ?>>
                <a href="<?php echo $this->url('game/feeds', array('name' => $urlName, 'category' => $categoryName)); ?>" class="<?php echo $categoryName; ?>" title="<?php echo $categoryTitle; ?>"><?php echo $this->translate(ucfirst($categoryName)); ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</aside>
<div id="main">
    <!--        <div id="categorySort">-->
    <!--        </div>-->
    <?php if ($feeds->count() > 0) { ?>
        <ul id="feeds">
            <?php
            foreach ($feeds as $feed) {
                echo $this->partial("/Feed/Partial/feed.phtml", array('feed' => $feed, 'user' => $user, 'likedFeeds' => $user->getInteractedFeedIds(false,"liked"),'favoriteFeeds' => $user->getInteractedFeedIds(false,"favorites")));
            }
            ?>
        </ul>
    <?php } else { ?>
        <div class="notFound"><?php echo $this->translate('There are no feeds available at the moment.'); ?></div>
    <?php } ?>
</div>