<?php
if(!empty($games)){
foreach($games as $game):
    $name = $game->getName();
    ?>
    <li>
        <a href="<?php echo $this->url('game/category',array('name' => $name)); ?>" title="<?php echo $name ?>">
            <span><?php echo substr($name,0,20); if(strlen($name) > 20) echo ' ..'?></span>
            <img src="<?php echo $this->basePath() . '/images/games/' . $game->getAvatar() . '-list-icon.jpg'; ?>">
        </a>
        <div class="gameMeta">
            <a href="<?php echo $this->url('game/profile',array('name' => $name)); ?>">Profile</a> •
            <a href="<?php echo $this->url('game/connect',array('type' => 'follow','name' => $name)); ?>">Follow</a> •
            <p class="gameFollowers"><?php echo count($game->getFollowers()); ?></p>
        </div>
    </li>
<?php endforeach;
}else{
    echo 'There were no games matched by the search criteria.';
}

?>