<div id="main">
	<div id="welcome">
		<span>
			<?php echo $general['welcome']; ?>
		</span>
	</div>
	<div id="latestFilms">
		<h1><?php echo $this->translate('LATEST FILMS'); ?></h1>
		<img class="sepLine" src="<?php echo $this->basePath() . '/images/line.png'; ?>" />	
		<ul>
		<?php
			$i = 0; 
			foreach($latestFilms as $film): 
				$snapshot = $film->getSnapshot();
		?>
			<li class="video-<?php echo $film->getVideoId();?>">
				<?php 
					if(!empty($snapshot)){
						if($i == 0){
							$snapshot = $film->getImageThumb(470,445);
							$i++;
						}else{
							$snapshot = $film->getImageThumb(234,220);
						}						
						echo '<img src="' . $this->basePath() . '/videos/' . $snapshot . '" />';
					}else{
						echo '<img src="' . $film->getVimeoThumb('large') . '" />';
					}
				?>
				<div class="filmTitle">
					<span>
					<?php if($locale == 'en_US'){
						echo $this->escapeHtml($film->getNameEn());
					}else{
						echo $this->escapeHtml($film->getName());
					} ?>	
					</span>	
					<span class="filmDate">
						<?php echo $film->getPostTime(); ?>
					</span>		
				</div>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>
	<div id="sponsors">
		<h1><?php echo $this->translate('THEY TRUST US'); ?></h1>	
		<img class="sepLine" src="<?php echo $this->basePath() . '/images/line.png'; ?>" />	
		<ul>
			<?php foreach($sponsors as $sponsor): ?>
				<li>
					<a href="<?php echo $sponsor->getUrl(); ?>" target="_blank"><img src="<?php echo $this->basePath() . '/images/sponsors/' . $sponsor->getImage(); ?>" /></a>
				</li>
			<?php endforeach; ?>
		</ul>	
	</div>		
</div>
