<div id="main">
	<div id="films">
		<ul class="categories">
			<?php 
				foreach($categories as $category): 
					$categoryName = ($locale == 'en_US') ? $category->getNameEn() : $category->getName();
			?>
				<li<?php echo ($activeCategory == $categoryName && isset($activeCategory)) ? ' class="active"' : ''; ?>>
					<a href="<?php echo $this->url('portfolio',array('category' => $categoryName)); ?>"><?php echo mb_strtoupper($categoryName, 'UTF-8') ?></a>
				</li>	
			<?php endforeach; ?>
		</ul>
		<ul class="films">
			<?php 
				if(count($films) > 0){
				foreach($films as $film): 
					$videoId = $film->getVideoId();
			?>
				
				<li class="video-<?php echo $videoId; ?>">
					<iframe id="ytPlayer" frameborder="0" src="http://player.vimeo.com/video/<?php echo $videoId; ?>?title=0&amp;byline=1&amp;portrait=1&amp;loop=0&amp;hd=1" style="width: 570px; height: 306px;"></iframe>					

					<?php if($locale == 'en_US'){
						$name = $film->getNameEn();
						$description = $film->getDescriptionEn();
					}else{
						$name = $film->getName();
						$description = $film->getDescription();
					} ?>
					<h2><?php echo $name; ?></h2>
					<span class="description"><?php echo $description; ?></span>	
										
					<!-- html5 way, may be implemented in the future  -->
					<!-- <video width="460" height="247">
					  <source src="<?php echo $this->basePath() . '/videos/' . $film->getVideo();?>">
					Your browser does not support the video tag.
					</video> -->
				</li>
			<?php endforeach; 
				}else{
					echo '<h2>' .$this->translate('There are no videos available for this category.') . '</h2>';
				}
			?>
		</ul>
	</div>
		<div id="sponsors">
			<h1><?php echo $this->translate('THEY TRUST US'); ?></h1>	
			<img class="sepLine" src="<?php echo $this->basePath() . '/images/line.png'; ?>" />	
			<ul>
				<?php foreach($sponsors as $sponsor): ?>
					<li>
						<a href="<?php echo $sponsor->getUrl(); ?>" target="_blank"><img src="<?php echo $this->basePath() . '/images/sponsors/' . $sponsor->getImage(); ?>" /></a>
					</li>
				<?php endforeach; ?>
			</ul>	
		</div>	
</div>
