<div id="login">
	<h1>Login</h1>
	
	<?php
	$form = $this->loginForm;
	$form->prepare();
	$form->setAttribute('action', $this->url('account-login'));
	?>
	<?php echo $this->form()->openTag($form) ?>
	        <?php #echo $this->formElementErrors($form->get('identity')) ?>
	
	        <div class="element">
	     	   <?php echo $this->formLabel($form->get('username')) ?>
         	   <?php echo $this->formInput($form->get('username')) ?>       
			</div>
	
	        <div class="element">
	     	   <?php echo $this->formLabel($form->get('password')) ?>
         	   <?php echo $this->formInput($form->get('password')) ?>   
			</div>
			
	        <div class="element">
	     	   <?php echo $this->formLabel($form->get('rememberme')) ?>
	        	<?php echo $this->formCheckbox($form->get('rememberme')) ?>
			</div>
			
	
			<?php #echo $this->formElement($form->get('security')); ?>
	        <div class="element">
	        	<?php echo $this->formSubmit($form->get('submit')); ?>
	        </div>
	
	<?php echo $this->form()->closeTag() ?>
</div>
