<h1>Register</h1>

<?php
$form = $registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('account-register'));
?>

<?php echo $this->form()->openTag($form) ?>
        <?php #echo $this->formElementErrors($form->get('identity')) ?>

        <div class="element">
        <?php echo $this->formRow($form->get('username')) ?>
		</div>

        <div class="element">
        <?php echo $this->formRow($form->get('password')) ?>
		</div>
		
        <div class="element">
        <?php echo $this->formRow($form->get('email')) ?>
		</div>
		

		<?php #echo $this->formElement($form->get('security')); ?>
        <div class="element">
        	<?php echo $this->formSubmit($form->get('submit')); ?>
        </div>

<?php echo $this->form()->closeTag() ?>


Already registered? <a href="<?php echo $this->url('account-login') ?>">Login!</a>